### PR TITLE
Add Elixir

### PR DESCRIPTION
**Pull request by jesse-c**
Adds Elixir Tree-sitter [grammar](https://github.com/elixir-lang/tree-sitter-elixir). AFAIK I've followed the steps correctly, but, I'm having some issues running the tests locally (an env issue, not with the project itself).

Thank you as well for making this!

### CODE REVIEW

**Comment by BrianHicks** [comment]
hey, looking great so far! I've made a few corrections that came up in CI.

As far as environment issues: you wouldn't happen to be on an M1 Mac, would you? I've just fixed the environment for that platform in `main`.

**Comment by BrianHicks** [comment]
anyway the snapshot looks pretty reasonable to me, so I'm going to merge this when it's green 👍

**Comment by jesse-c** [comment]
Thank you for the corrections. I'll re-order the languages elsewhere too!

> As far as environment issues: you wouldn't happen to be on an M1 Mac, would you? I've just fixed the environment for that platform in main.

I do. I'll try it out. Thanks!

**Comment by BrianHicks** [comment]
by the way: may I ask what you're using tree-grepper for? Always curious to hear people's use-cases!

**Comment by jesse-c** [comment]
Sure! One common use case for me is opening a specific module in a large Elixir project. In Elixir, modules generally follow file names so that's how I normally would.

For example, `/lib/transport/car/driver.ex` would be `Transport.Car.Driver`. I'd prefer to have an intelligent fuzzy search by module names. If there was also `Transport.Plane.Pilot` and I start typing "trc" then fuzzy matching resulting in `Transport.Car.Driver` would be very handy.

That's quite a contrived example though. In the large Elixir project, you could have a common concept name all over the place.

What I next need to do is refine a query that would give me all the module names (I don't fully get the query system yet and the grammars can be so different) and then use it somehow in Neovim (e.g. through `telescope.nvim`).

I could use a search through LSP workspace symbols, but I won't have loaded all of them.

**Comment by BrianHicks** [comment]
oh, that's a cool idea. Looking at the Elixir trees it looks like this one is not super intuitive because `defmodule` is not a part of the grammar, but just another function call. I wanted to figure it out because I was curious, so here's the query:

```
tree-grepper -q elixir '(call (identifier)@_fn (arguments (_))@args (do_block) (#eq? @_fn defmodule))'
```

(although note that that will match on multiple arguments to `defmodule`.)

How I figured it out:

1. I looked at the tree-sitter-elixir corpus tests (`test/corpus/integration/module_definition.txt` in the tree-sitter-elixir) codebase. I noticed that `defmodule` ends up as a `call` node, with the name as the argument.
2. `call` nodes always seem to have an `identifier` as the first argument. That smells like a string, so I captured it as `_fn` (with leading underscore so tree-grepper doesn't include it in the output) and then matched it with `#eq?` (which can appear anywhere in the query, I think, but which I always put at the end by habit)
3. the rest is just writing down the arguments. I just used the corpus tests as a cheat sheet.
4. I noticed that this is kinda slow (~600ms on a smallish project.) Unfortunately, I think this might not be the best case for tree-grepper because the query system has to examine *all* the `call` nodes. I tried a couple things to get it faster (mostly by being more specific) but nothing stuck. For reference, I've attached a benchmark. `rg` might be a much better tool for the thing you described if you're OK with having unstructured line output instead of structured syntax tree stuff. 😓

```
$ hyperfine "tree-grepper -q elixir '(call (identifier)@_fn . (arguments (_))@args . (do_block) (#eq? @_fn defmodule))'" "rg defmodule"
Benchmark 1: tree-grepper -q elixir '(call (identifier)@_fn . (arguments (_))@args . (do_block) (#eq? @_fn defmodule))'
  Time (mean ± σ):     673.5 ms ±   0.5 ms    [User: 670.1 ms, System: 7.6 ms]
  Range (min … max):   672.7 ms … 674.1 ms    10 runs

Benchmark 2: rg defmodule
  Time (mean ± σ):       4.3 ms ±   0.5 ms    [User: 1.9 ms, System: 1.9 ms]
  Range (min … max):     3.5 ms …   7.1 ms    358 runs

  Warning: Command took less than 5 ms to complete. Results might be inaccurate.

Summary
  'rg defmodule' ran
  157.38 ± 18.34 times faster than 'tree-grepper -q elixir '(call (identifier)@_fn . (arguments (_))@args . (do_block) (#eq? @_fn defmodule))''
```

**Comment by jesse-c** [comment]
I don't feel as bad not quite getting the query syntax after seeing your result. 😅 Thank you for the detailed explanation!

That's unfortunate about the speed. `rg` is what I've been using so far. I usually chuck in some `defmo` to filter it down quickly at first. The structured nature was my motivation for wanting to try this with Tree-sitter.

I'll try it out on the large project (more like huge project) and see what the speed is like. There may actually be a trade-off where I'm spending a few hundred millisecond doing the `defmodule` filtering with `rg` that would counteract the Tree-sitter speed. That does just make me think though that perhaps I should have a "prepared search" for `rg` to save that little time.

**Comment by jesse-c** [comment]
Out of curiosity, do you find yourself using tree-grepper day-to-day when you're in the thick of coding? Or more for when you're analysing a codebase?

I'm wondering as well if conceptually something like tree-grepper could be expanded into some sort of semantic search and replace à la https://comby.dev.

**Comment by BrianHicks** [comment]
so I couldn't leave well enough alone and wondered if I could reduce the query (perhaps beyond the point of usefulness) to get it faster. Turns out matching a single node—even on a regex—is quite a bit faster. For example, `tree-grepper -q elixir '((alias)@out (#match? @out "[A-Z][A-Za-z0-9\.]*"))'` completes in ~15ms in the same codebase. I think there may be something about the tree walking that's slowing things down.

> Out of curiosity, do you find yourself using tree-grepper day-to-day when you're in the thick of coding? Or more for when you're analysing a codebase?

Yeah, I use it day to day for two big things:

1. writing tools that walk an import graph to only build the right entrypoints in a big Elm project, as detailed in https://bytes.zone/posts/tree-grepper/
2. jumping to a name in a single file, as implemented in https://git.bytes.zone/brian/dotfiles.nix/src/commit/a9d94b719c7abe91ba6c39d32048e0d2dd5c648a/dotfiles/kakoune/rc/tree-grepper.kak

> I'm wondering as well if conceptually something like tree-grepper could be expanded into some sort of semantic search and replace à la https://comby.dev.

I really like Comby's query syntax, TBH. I would love for you to have been able to just say `tree-grepper -q elixir 'defmodule {X}'`. This might be a point of interest for an eventual tree-grepper 3.0—with a focus on query speed, of course!

**Comment by jesse-c** [comment]
> `tree-grepper -q elixir '((alias)@out (#match? @out "[A-Z][A-Za-z0-9\.]*"))'`

Interesting! Where in this is it restricting it to `defmodule`s? I know `alias` is an Elixir keyword.

Those are some interesting uses! Funnily enough, I used Elm professionally from 2018-2019.

Yup, I'm a fan of Comby. I've had a few really successful uses of it that would've been very painful otherwise. I'm a big fan of structural editing (or whatever it's called), so I think tree-grepper, etc are the right tools to finally make it mainstream!

As I master the tree-sitter query lang, I'm sure I'll find more uses of it to supplant/replace daily things I do.

**Comment by BrianHicks** [comment]
> Interesting! Where in this is it restricting it to defmodules? I know alias is an Elixir keyword.

It's not! 😅 I did simplify it beyond the point of uselessness after all. It's just looking for aliases matching that regular expression.

> As I master the tree-sitter query lang, I'm sure I'll find more uses of it to supplant/replace daily things I do.

Please report back as you do. I'd love to hear what you come up with!

**Comment by jesse-c** [comment]
Will do!

**Pull request merged**
