### PR TITLE
Add support tree-sitter-c

### PR DESCRIPTION
**Pull request by Mephistophiles**

### CODE REVIEW

**Comment by BrianHicks** [comment]
hey @Mephistophiles! Thanks for opening this! It looks pretty good to me, and I plan to merge it, but it looks like there's a conflict with the `Cargo.toml` (Dependabot merged some updates that duplicated your work.) Would you mind fixing the merge conflict?

**Comment by Mephistophiles** [comment]
Hi, @BrianHicks. No problem =)

**Comment by BrianHicks** [comment]
Hmm… I've been waiting for CI statuses to show up here and they haven't. Really weird, especially because I don't see a way to kick off a run manually. 🤔 Maybe it was the force-pushes?

I'm going to try and push a nixpkgs update to this branch to see if I can get it unstuck and update nixpkgs at the same time. If it causes a bunch of failures we can back off.

**Comment by BrianHicks** [comment]
it worked, and away we go! Thanks for this PR, and for upgrading Clap @Mephistophiles!

**Pull request merged**
